### ISSUE TITLE
Proof of Work

### ISSUE THREAD

**Issue by pascalbros** [IOTA-Ledger/blue-app-iota#10]
First of all, thanks for this awesome implementation, on my i7 takes only 0.002 secs to generate the address.
Is there any plan for the Proof of Work written in C?
The C implementation can help to speed up the Java and Swift IOTA lib as well.

Thanks, Pascal

**Comment by Wollac** [comment]
Hi,
thank you for the question.
Unfortunately, currently we are 100% focused on the tasks and special requirements for a secure Ledge Nano S application. As the Ledger is a little slower (address generation takes about 2s) doing PoW on the device is complete out of the question and not necessary for our purposes, since the PoW can be performed independently from transaction signing.
So our plan only includes address generation, bundle hashing and transaction signing, which are of course also important parts of any IOTA lib...
Apart from that, there already exists ccurl offering a C version of the Curl algorithm.

Cheers.

**Comment by muXxer** [comment]
See wollacs answer. Closed!
